### ISSUE TITLE
[Suggestion/Request][1.16.4][Forge] Bedrock block replacement

### ISSUE THREAD

**Issue by drakray** [nevoka-be/Issues#4]
Hi there, just a quick suggestion/request
Could it be possible to have a config to replace the generated bedrock with another block, maybe a per dimension config, like
```
replaceBy = ["mod:dimension":"mod:block","minecraft:the_nether":"minecraft:obsidian","minecraft:overworld":"minecraft:gravel"]
```

That would be very nice, especially for the Nether to be able to go over and build there in survival

Thank you for the consideration, and for your good work :)

**Comment by JayJay1989** [comment]
Will try this later today

**Comment by JayJay1989** [comment]
Ok, got some progress, as if TOML config doesn't support "key":"value" i changed it a bit.

```toml
[General]
	#A list of dimension ids that this mod should filter based on the 'Act as whitelist' setting.
	#Modded dimensionFilter will need to be added here to be affected.
	#Adding a '=>' behind the dimension id, you can change the layer to another block.
	#Adding nothing will result in default bedrock
	dimensionFilter = ["minecraft:overworld=>minecraft:dirt", "minecraft:the_nether"]
	#Set to false to make the dimension whitelist act as a blacklist.
	isWhitelist = true
```

by adding a `=>` behind the dimension id, it is possible to replace the bedrock with dirt in the overworld, see the example above.

[betterbedrockgenerator-1.16.4-0.1.2.jar.zip](https://github.com/nevoka-be/Issues/files/5659106/betterbedrockgenerator-1.16.4-0.1.2.jar.zip)
